version: 1.1.0.{build}
image: Visual Studio 2019

environment:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: true

build_script:
- ps: >-
    dotnet --info

    dotnet restore

    dotnet run -c Release -p ./tests/Wox.Plugin.Bang.Tests.fsproj -- --summary --colours 0

    dotnet pack -c Release

artifacts:
    - path: Wox.Plugin.Bang\bin\Release\*.nupkg