version: 1.1.0.{build}
image: Visual Studio 2019

environment:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: true

before_build:
- ps: >-
    dotnet --info

    dotnet tool restore

    dotnet paket restore

build_script:
- ps: >-
    dotnet run -c Release -p ./tests/Wox.Plugin.Bang.Tests.fsproj -- --summary --colours 0

    dotnet pack -c Release

after_build:
- ps: >-
    $zipSettings = @{
        Path = ".\Wox.Plugin.Bang\bin\Release\net462\*.dll", ".\Wox.Plugin.Bang\bin\Release\net462\plugin.json", ".\Wox.Plugin.Bang\bin\Release\net462\*.png"
        DestinationPath = "plugin.zip"
    }

    Compress-Archive @zipSettings

    Rename-Item plugin.zip Wox.Plugin.Bang.wox

artifacts:
    - path: Wox.Plugin.Bang\bin\Release\*.nupkg
    - path: '*.wox'