version: 1.3.0.{build}
image: Visual Studio 2022

environment:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: true

before_build:
    - ps: dotnet --info
    - ps: dotnet tool restore
    - ps: dotnet paket restore

build_script:
    - ps: dotnet pack -c Release

after_build:
- ps: >-
    $zipSettings = @{
        Path = Get-ChildItem -Path ".\src\bin\Release\*" -Exclude "*.nupkg"
        DestinationPath = "Flow.Plugin.Bang.zip"
    }

    Compress-Archive @zipSettings

test_script:
    - ps: dotnet run --no-build -c Release --project ./tests/ -- --summary

artifacts:
    - path: src\bin\Release\*.nupkg
    - path: '*.zip'