version: 1.1.0.{build}
image: Visual Studio 2019

environment:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: true

before_build:
- ps: >-
    dotnet --info

    dotnet tool restore

    dotnet paket restore

build_script:
- ps: >-
    dotnet run -c Release -p ./tests/Flow.Plugin.Bang.Tests.fsproj -- --summary --colours 0

    dotnet pack -c Release

after_build:
- ps: >-
    $zipSettings = @{
        Path = ".\src\bin\Release\net5.0-windows\*"
        DestinationPath = "Flow.Plugin.Bang.zip"
    }

    Compress-Archive @zipSettings

artifacts:
    - path: src\bin\Release\*.nupkg
    - path: '*.zip'